projectId: app-MZ3rwpaSk96MC2HcKWPfTc
appName: success
description: This a test project
version: "1.0"
hostName: example.test
clusterURL: default
clusterIPs:
- 190.89.89.0
monitoring: true
microservices:
  CartService:
    serviceName: cartservice
    avgReplicas: 1
    minReplicas: 1
    maxReplicas: 1
    dockerImage: wwaeqw
    containerPort: 8080
  OrderService:
    serviceName: orderservice
    avgReplicas: 1
    minReplicas: 1
    maxReplicas: 1
    dockerImage: sjhdf
    containerPort: 8080
    serviceEvaluation:
      kubeConfigType:
      - statefulSetBased
  UserService:
    serviceName: userservice
    avgReplicas: 1
    minReplicas: 1
    maxReplicas: 1
    dockerImage: wasded
    containerPort: 8080
evaluationResult:
  language: Java
  database: MySQL
  microservices:
  - CartService
  - OrderService
  - UserService
